# Домашнее задание 1
В файле `HW01.ipynb` должны быть:

1. Импорт библиотеки NumPy с общепринятым сокращением.
2. Примеры создания массивов:
   - из обычных списков;
   - с использованием функций `zeros`, `ones`, `arange` или аналогичных.
3. Демонстрация атрибутов:
   - вывод формы (shape) и типа данных (dtype) для одного из массивов.
4. Примеры индексирования и срезов:
   - получение отдельного элемента;
   - извлечение подмассива с помощью среза.
5. Примеры векторных операций и базовых статистик:
   - поэлементное сложение или умножение массивов;
   - вычисление средней величины (`mean`) или другой простой статистики.

Желательно добавить несколько комментариев в коде, кратко поясняющих, что делает каждая операция.

---

In [3]:
# 1
import numpy as np

In [4]:
# 2
# из обычного списка
arr_example = [1, 2, 3.4, 5]

numpy_arr_1 = np.array(arr_example)

numpy_arr_1

array([1. , 2. , 3.4, 5. ])

In [5]:
#  с использованием функций `zeros`, `ones`, `arange` или аналогичных.

numpy_arr_2 = np.zeros([10,4]) # матрица из нулей, 10 строк, 4 столбца
numpy_arr_3 = np.ones([3, 6]) # матрица из единиц, 3 строки, 6 столбцов
numpy_arr_4 = np.arange(10) # вектор из чисел от 0 до 10

In [6]:
numpy_arr_2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
numpy_arr_3

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [8]:
numpy_arr_4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# 3
numpy_arr_3.shape # размер массива, 3 строки, 6 столбцов

(3, 6)

In [10]:
numpy_arr_4.dtype # тип данных в массиве, int32

dtype('int32')

In [11]:
# 4 индексирование и срезы

numpy_arr_3[0, 1] # получение отдельного элемента, 1 строка, 2 столбец

1.0

In [12]:
numpy_arr_4[4:6] # подмассив, от 5 элемента до 7, не включая последний

array([4, 5])

In [13]:
# 5
example_1 = np.arange(5)
example_2 = np.arange(5)

sum_arrays = example_1 + example_2 # поэлементное сложение
sum_arrays

array([0, 2, 4, 6, 8])

In [14]:
mul_array = example_1 * example_2 # поэлементное умножение
mul_array

array([ 0,  1,  4,  9, 16])

In [15]:
# вычисление средней величины (mean) или другой простой статистики
mean = np.mean(sum_arrays) # средняя величина
mean

4.0

In [34]:
# сумма
summary = np.sum(sum_arrays)
summary

20

In [16]:
median = np.median(sum_arrays) # медиана
median

4.0

In [17]:
std = round(np.std(sum_arrays), 3) # с.к. отклонение
std

2.828

In [46]:
# максимум и минимум
maximum = np.max(sum_arrays)
minimum = np.min(sum_arrays)

maximum, minimum

(8, 0)